# Generated by Django 4.2.2 on 2023-06-21 21:48

from django.db import migrations, models
import photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='photos/', validators=[photos.models.Photo.validate_max_img_size]),
        ),
    ]
