# Generated by Django 4.2.1 on 2023-06-07 19:17

from django.db import migrations, models
import photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='images', validators=[photos.models.Photo.validate_max_img_size]),
        ),
    ]
