# Generated by Django 4.2.1 on 2023-06-08 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_photo'),
        ('common', '0002_rename_tagged_photo_comment_to_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='PhotoComment',
        ),
    ]
