# Generated by Django 4.2.1 on 2023-06-08 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_photo'),
        ('common', '0003_rename_comment_photocomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocomment',
            name='comment_text',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PhotoLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_photo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_photo_likes', to='photos.photo')),
            ],
        ),
    ]
