# Generated by Django 4.2.1 on 2023-06-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_photocomment_comment_text_photolike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocomment',
            name='comment_text',
            field=models.TextField(max_length=300),
        ),
    ]
