# Generated by Django 4.2.1 on 2023-06-09 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_alter_photo_description'),
        ('common', '0005_alter_photocomment_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocomment',
            name='to_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_comments', to='photos.photo'),
        ),
    ]
