# Generated by Django 4.2.2 on 2023-06-24 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='passwords',
            new_name='password',
        ),
    ]
